apiVersion: v1
kind: Service
metadata:
  name: guildship-core-service
spec:
  ports:
    - port: 8080
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: guildship-core
  type: LoadBalancer
