apiVersion: v1
kind: Service
metadata:
  name: gs-core-service
spec:
  ports:
    - port: 8080
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: gs-core
  type: LoadBalancer
